version: '3.8'
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=db_files
      - MYSQL_USER=root
      - MYSQL_PASSWORD=
    ports:
      - "3310:3306"
    volumes:
      - db:/var/lib/mysql
  app:
    depends_on:
      - mysqldb
    build: ./dist
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=mysqldb
      - DB_USER=root
      - DB_PASSWORD=
      - DB_NAME=db_files
      - DB_PORT=3306
    stdin_open: true
    tty: true
volumes: 
  db:
